version: '3.7'
services:
  wppconnect:
    build:
      context: .
      dockerfile: Dockerfile
    image: wppconnect/server
    container_name: wppconnect
    restart: unless-stopped
    ports:
      - '3333:3333'
    volumes:
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
      - ./userDataDir:/usr/src/wpp-server/userDataDir
      - ./src/swagger.json:/usr/src/wpp-server/src/swagger.json
    environment:
      - TZ=America/Sao_Paulo
    command: 'yarn start'

  autoserp-mongo:
    container_name: wpp-connect_autoserp-mongo
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=4c5c50327ff2dbe8aba7
      - MONGO_INITDB_DATABASE=tokens
    ports:
      - "27017:27017"
    command: mongod --auth

volumes:
  mongodb_data: {}
  wppconnect_tokens: {}
