version: "3.8"

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
      - ./userDataDir:/usr/src/wpp-server/userDataDir
    ports:
      - "21465:21465"
    depends_on:
      - autoserp-mongo
    environment:
      - NODE_ENV=production

  autoserp-mongo:
    container_name: wpp-connect_autoserp-mongo
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=4c5c50327ff2dbe8aba7
      - MONGO_INITDB_DATABASE=tokens
    ports:
      - "27017:27017"
    command: mongod --auth

volumes:
  mongodb_data: {}
  wppconnect_tokens: {}
